- hosts: servers
  tasks:
  - name: Update system
    become: true
    become_user: vova
    shell:      sudo apt update && sudo apt -y upgrade && sudo apt update

  - name: Add Node.js APT Repository
    shell:      sudo apt -y install curl dirmngr apt-transport-https lsb-release ca-certificates && curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -

  - name: Install Node.js 12
    shell: sudo apt -y install nodejs
  
