- hosts: 10.0.1.4
  tasks:
  - name: init database
    become: true
    become_user: vova
    shell:   npm --prefix  /vova/moshe/bootcamp   run initdb

- hosts: 10.0.1.5
  tasks:
  - name: init database
    become: true
    become_user: vova
    shell:   npm --prefix  /vova/moshe/bootcamp   run initdb
